import Head from 'next/head'
import { Inter } from 'next/font/google'
import Sidebar from '@/Components/Sidebar'
import Feed from '@/Components/Feed'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto'>
       <Sidebar/>
       <Feed/>
      </main>
      
    </div>
  )
}
